# Generated by Django 2.1.12 on 2020-06-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pointing_users',
        ),
        migrations.AlterField(
            model_name='movie_star_point',
            name='star_point',
            field=models.IntegerField(default=0),
        ),
    ]
