# Generated by Django 2.1.12 on 2020-06-13 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20200613_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pointing_users',
            field=models.ManyToManyField(related_name='pointed_movies', through='movies.Movie_Star_Point', to=settings.AUTH_USER_MODEL),
        ),
    ]
