# Generated by Django 2.1.12 on 2020-06-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_pointing_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_star_point',
            old_name='user',
            new_name='poing_user',
        ),
        migrations.RenameField(
            model_name='movie_star_point',
            old_name='movie',
            new_name='pointed_movie',
        ),
    ]
