# Generated by Django 2.1.12 on 2020-06-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200613_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_star_point',
            old_name='poing_user',
            new_name='pointing_user',
        ),
    ]
