# Generated by Django 2.1.12 on 2020-06-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='point',
        ),
    ]
